name: Notify Minus Alert

on:
  schedule:
    - cron: '0 23 * * *'  # 毎日日本時間9:00に実行（後で直す）
  workflow_dispatch:     # 手動実行もできる

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP request to /run_notify
        run: |
          curl -X GET https://minus-alert.onrender.com/run_notify
